### ISSUE TITLE
Startup error via AWS CloudShell - libssl

### ISSUE THREAD

**Issue by brack** [awslabs/amazon-qldb-shell#205] opened 2021-09-28 22:04 UTC
```
$ ./qldb --ledger vehicle-registration
./qldb: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

I launched a cloudshell, set up aws config, took the linux binary, uploaded it to my cloudshell, granted execution permissions, and then ran it, which generated the above error. 

Context: I'm trying to simulate the scenario where a developer might want to take the binary with them to various remote hosts.

Looking at a couple issues online, it seems like it could be a dependency issue or path issue. Perhaps in that case, we can just update the readme prerequisites.

**Comment by brack** [comment] 2021-09-28 22:11
```
$ ldconfig -p | grep libssl
        libssl3.so (libc6,x86-64) => /lib64/libssl3.so
        libssl.so.10 (libc6,x86-64) => /lib64/libssl.so.10
```

**Comment by marcbowes** [comment] 2021-09-28 22:36
This looks like a regression, as I fixed this in bc090f1736465484859c11bfc80c3cd86f57cdf9.

**Comment by marcbowes** [comment] 2021-09-28 22:50
On macOS, `cargo tree` differs from on Linux:

```
│   ├── hyper-rustls v0.22.1 (*)
```

vs

```
│   ├── hyper-tls v0.5.0
│   │   ├── bytes v1.1.0
│   │   ├── hyper v0.14.10 (*)
│   │   ├── native-tls v0.2.7
│   │   │   ├── log v0.4.14 (*)
│   │   │   ├── openssl v0.10.35
```

**Comment by marcbowes** [comment] 2021-09-29 04:08
Fixed via related. Please reopen if still an issue.

**Closed by marcbowes** 2021-09-29 04:08 UTC
